# Generated by Django 3.2.5 on 2022-04-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.CharField(max_length=20)),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자(들)',
                'db_table': 'opd_admin',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('contents', models.TextField()),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('viewcnt', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.admin')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항(들)',
                'db_table': 'opd_notice',
            },
        ),
        migrations.CreateModel(
            name='NoticeImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='noticeimg_img/')),
                ('img_original', models.TextField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.notice')),
            ],
            options={
                'verbose_name': '공지사항 이미지',
                'verbose_name_plural': '공지사항 이미지(들)',
                'db_table': 'opd_noticeimg',
            },
        ),
    ]
