# Generated by Django 3.2.5 on 2022-04-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220401_1526'),
        ('developer', '0003_remove_developer_language'),
        ('board', '0003_remove_board_language'),
        ('company', '0004_remove_company_language'),
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
