# Generated by Django 3.2.5 on 2022-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '언어',
                'verbose_name_plural': '언어(들)',
                'db_table': 'opd_language',
            },
        ),
    ]
