# Generated by Django 3.2.5 on 2022-03-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='language',
            field=models.ManyToManyField(to='project.Language'),
        ),
        migrations.AddField(
            model_name='developer',
            name='likeproject',
            field=models.ManyToManyField(to='project.Project'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='이메일'),
        ),
    ]
