# Generated by Django 3.2.5 on 2022-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='likeproject',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
