# Generated by Django 3.2.5 on 2022-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_language'),
        ('developer', '0003_remove_developer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='language',
            field=models.ManyToManyField(to='admin.Language'),
        ),
    ]
