# Generated by Django 3.2.5 on 2022-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_language'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(to='admin.Language'),
        ),
    ]
