# Generated by Django 3.2.5 on 2022-04-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='recruit_language',
            name='language',
        ),
    ]
