# Generated by Django 3.2.5 on 2022-03-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20220331_1354'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(to='project.Language'),
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='developer.Developer'),
        ),
        migrations.CreateModel(
            name='RecruitOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name': '프로젝트 모집처리',
                'verbose_name_plural': '프로젝트 모집(들)',
                'db_table': 'opd_recruitok',
            },
        ),
        migrations.CreateModel(
            name='Recruit_Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.language')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.recruit')),
            ],
            options={
                'verbose_name': '프로젝트 모집 언어',
                'verbose_name_plural': '프로젝트 모집 언어(들)',
                'db_table': 'opd_recruit_language',
            },
        ),
    ]
