# Generated by Django 3.2.5 on 2022-04-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_language'),
        ('project', '0002_auto_20220401_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ManyToManyField(to='admin.Language'),
        ),
        migrations.AddField(
            model_name='recruit_language',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.language'),
        ),
    ]
