# Generated by Django 3.2.5 on 2022-03-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220331_1354'),
        ('project', '0002_auto_20220331_1356'),
    ]

    operations = [
    ]
