# Generated by Django 3.2.5 on 2022-04-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220331_1844'),
        ('project', '0002_auto_20220331_1847'),
    ]

    operations = [
    ]
