# Generated by Django 3.2.5 on 2022-04-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_language'),
        ('project', '0002_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit_language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.language'),
            preserve_default=False,
        ),
    ]
