# Generated by Django 3.2.5 on 2022-04-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_language'),
        ('project', '0003_recruit_language_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit_language',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.language'),
        ),
        migrations.AlterField(
            model_name='recruit_language',
            name='recruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.recruit'),
        ),
    ]
