# Generated by Django 3.2.5 on 2022-03-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.ManyToManyField(to='project.Language', verbose_name='사용언어'),
        ),
        migrations.AddField(
            model_name='company',
            name='likeproject',
            field=models.ManyToManyField(to='project.Project', verbose_name='좋아요한 프로젝트'),
        ),
    ]
