# Generated by Django 3.2.5 on 2022-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_likeproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
        migrations.AddField(
            model_name='company',
            name='address_detail',
            field=models.CharField(default=' ', max_length=100, verbose_name='회사상세주소'),
            preserve_default=False,
        ),
    ]
