# Generated by Django 3.2.5 on 2022-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_language'),
        ('company', '0004_auto_20220401_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.ManyToManyField(to='admin.Language', verbose_name='사용언어'),
        ),
    ]
