# Generated by Django 3.2.5 on 2022-04-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('regdate', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('viewcnt', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판(들)',
                'db_table': 'opd_board',
            },
        ),
        migrations.CreateModel(
            name='Boardimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(default='', upload_to='boardimg_img/')),
                ('img_original', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '게시판그림',
                'verbose_name_plural': '게시판그림(들)',
                'db_table': 'opd_boardimg',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100, verbose_name='댓글내용')),
                ('regdate', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('private', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글(들)',
                'db_table': 'opd_comment',
            },
        ),
    ]
