# Generated by Django 3.2.5 on 2022-04-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
        ('admin', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='boardimg',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판'),
        ),
        migrations.AddField(
            model_name='board',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='board',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.language', verbose_name='언어'),
        ),
    ]
