# Generated by Django 3.2.5 on 2022-03-31 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20220331_1354'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100, verbose_name='댓글내용')),
                ('regdate', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('private', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글(들)',
                'db_table': 'opd_Comment',
            },
        ),
    ]
