# Generated by Django 3.2.5 on 2022-04-01 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20220331_1354'),
        ('project', '0003_merge_0002_auto_20220331_1844_0002_auto_20220331_1847'),
        ('board', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardimg',
            name='boardimg',
        ),
        migrations.AddField(
            model_name='boardimg',
            name='img',
            field=models.FileField(default='', upload_to='boardimg_img/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.language', verbose_name='언어'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='opd_comment',
        ),
    ]
