# Generated by Django 3.2.5 on 2022-03-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comment_table'),
        ('board', '0003_auto_20220331_1519'),
    ]

    operations = [
    ]
