# Generated by Django 3.2.5 on 2022-04-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_language'),
        ('board', '0003_remove_board_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.language', verbose_name='언어'),
        ),
    ]
