# Generated by Django 3.2.5 on 2022-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_merge_20220331_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardimg',
            name='boardimg',
        ),
        migrations.AddField(
            model_name='boardimg',
            name='img',
            field=models.FileField(default='', upload_to='boardimg_img/'),
        ),
    ]
