# Generated by Django 3.2.5 on 2022-03-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20220331_1354'),
        ('board', '0005_auto_20220331_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer', verbose_name='작성자'),
        ),
    ]
